#!/bin/bash

# 🧪 Test Vercel Deployment Script
# Creates a test PR to verify preview deployment

set -e

echo "🧪 Testing Vercel Preview Deployment"
echo "====================================="
echo ""

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Generate branch name
BRANCH_NAME="test/vercel-deployment-$(date +%s)"

echo -e "${BLUE}Creating test branch...${NC}"
git checkout -b "$BRANCH_NAME"

echo -e "${BLUE}Creating empty commit...${NC}"
git commit --allow-empty -m "test: verify vercel preview deployment

This is a test PR to verify:
- ✅ GitHub Actions workflow runs
- ✅ Vercel preview deployment succeeds
- ✅ Preview URL is generated
- ✅ PR comment with URL is posted

Auto-generated by: scripts/test-vercel-deployment.sh"

echo -e "${BLUE}Pushing to remote...${NC}"
git push origin "$BRANCH_NAME"

echo -e "${BLUE}Creating pull request...${NC}"
gh pr create \
  --title "🧪 Test: Vercel Preview Deployment" \
  --body "## Test Vercel Preview Deployment

This is an automated test PR to verify the Vercel preview deployment workflow.

### Checks to verify:
- [ ] CI workflow passes
- [ ] Deploy Preview workflow runs
- [ ] Preview URL is generated
- [ ] Preview deployment is accessible
- [ ] PR comment appears with preview link

### Expected Result:
A comment should appear on this PR with:
\`\`\`
🚀 **Preview Deployed**

✅ Preview URL: https://news-git-${BRANCH_NAME}-yunaamelia.vercel.app

Changes are live and ready for review!
\`\`\`

---
Auto-generated by: \`scripts/test-vercel-deployment.sh\`" \
  --label "test" \
  --label "deployment"

echo ""
echo -e "${GREEN}✅ Test PR created!${NC}"
echo ""
echo "Monitor workflow:"
echo "  gh run watch"
echo ""
echo "View PR:"
echo "  gh pr view --web"
echo ""
echo "After verification, close PR with:"
echo "  gh pr close $BRANCH_NAME"
echo "  git checkout main"
echo "  git branch -D $BRANCH_NAME"
echo "  git push origin --delete $BRANCH_NAME"
